[tool.poetry]
name = "phoenix-documentation"
version = "9999"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.9"
doc8 = "==0.11.1"
docutils = "==0.17.0"
fonttools = {version = "==4.33.3", extras = ["woff"]}
furo = "==2022.9.29"
latex = "==0.7.0"
packaging = "==20.9"
sphinx = "==4.5.0"
sphinx-copybutton = "==0.5.1"
sphinx-hoverxref = "==1.0.1"
sphinx-notfound-page = "==0.8.0"
sphinx_design = "==0.3.0"
sphinxcontrib-ghcontributors = "==0.2.3"
sphinxcontrib-htmlhelp = "==2.0.0"
sphinxcontrib-images = "==0.9.4"
sphinxcontrib-serializinghtml = "==1.1.5"
sphinxcontrib-svg2pdfconverter = "==1.2.0"
sphinxext-delta = "==0.2.0"
sphinxext-mimic = "==0.1.1"
sphinxext-opengraph = "==0.4.1"
sphinxext-rediraffe = "==0.2.5"
sphinxext-remoteliteralinclude = "==0.3.0"
urllib3 = ">=1.26.6, <2.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"